import {validate,type Project} from './model';
import {validateWorkspace,legacyWorkspace,type WorkspaceDraft} from './workspace';
let token='';export let dataDirectory='';
export async function init(){const v=await (await fetch('/api/session')).json();token=v.token;dataDirectory=v.dataDirectory;}
export async function api(route:string,body?:unknown,binary=false){const r=await fetch('/api/'+route,{method:body===undefined?'GET':'POST',headers:{'x-bio-token':token,'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok){const e:any=Error((await r.json()).error);e.status=r.status;throw e;}return binary?r.blob():r.json();}
export async function importFile(file:File){const pack=file.name.toLowerCase().endsWith('.biozip');const r=await fetch('/api/'+(pack?'unpack':'image?name='+encodeURIComponent(file.name)),{method:'POST',headers:{'x-bio-token':token,'content-type':'application/octet-stream'},body:file});if(!r.ok)throw Error((await r.json()).error);return validate(await r.json());}
let database:Promise<IDBDatabase>|undefined;
function db(){return database??=new Promise((resolve,reject)=>{const r=indexedDB.open('bio-picture-editor-v2.1-webui',1);r.onupgradeneeded=()=>r.result.createObjectStore('draft');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function saveWorkspace(workspace:WorkspaceDraft){const d=await db();return new Promise<void>((resolve,reject)=>{const tx=d.transaction('draft','readwrite'),store=tx.objectStore('draft');store.put(workspace,'workspace');const active=workspace.documents.find(v=>v.project.id===workspace.activeId);if(active)store.put(active.project,'current');else store.delete('current');tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
export async function readWorkspace(){const d=await db();return new Promise<WorkspaceDraft|undefined>((resolve,reject)=>{const store=d.transaction('draft').objectStore('draft'),r=store.get('workspace');r.onsuccess=()=>{try{if(r.result){resolve(validateWorkspace(r.result));return;}const legacy=store.get('current');legacy.onsuccess=()=>{try{resolve(legacy.result?legacyWorkspace(legacy.result):undefined);}catch(e){reject(e);}};legacy.onerror=()=>reject(legacy.error);}catch(e){reject(e);}};r.onerror=()=>reject(r.error);});}
export async function saveDraft(p:Project){return saveWorkspace(legacyWorkspace(p));}
export async function readDraft(){const workspace=await readWorkspace();return workspace?.documents.find(d=>d.project.id===workspace.activeId)?.project;}
export function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
