import {z} from 'zod';
const num=z.number().finite().min(-100000).max(100000), positive=z.number().finite().positive().max(100000);
const color=z.string().regex(/^#[0-9a-fA-F]{6}$/);
export const StyleSchema=z.object({color,strokeWidth:positive.max(500),headSize:positive.max(1000),dash:z.boolean(),contrast:z.boolean(),fontSize:positive.max(1000),font:z.enum(['BioSans','Microsoft YaHei','SimSun']),bold:z.boolean(),align:z.enum(['left','center','right']),textOutline:z.boolean(),background:color,backgroundOpacity:z.number().min(0).max(1),fill:color,fillOpacity:z.number().min(0).max(1)}).strict();
export const AnnotationSchema=z.object({id:z.string().uuid(),type:z.enum(['arrow','line','text','callout','rectangle','ellipse']),imageId:z.string().uuid(),geometry:z.object({x:num,y:num,x2:num,y2:num,width:positive,height:positive,unit:z.literal('image-pixel')}).strict(),style:StyleSchema,label:z.string().max(5000),description:z.string().max(10000),visible:z.boolean(),locked:z.boolean(),zIndex:z.number().int().min(0),status:z.enum(['user','suggested','confirmed'])}).strict();
export const ProjectSchema=z.object({format:z.literal('bio-annotation'),version:z.literal(1),id:z.string().uuid(),revision:z.number().int().nonnegative(),title:z.string().max(300),caption:z.string().max(10000),image:z.object({id:z.string().uuid(),name:z.string().max(300),mime:z.enum(['image/png','image/jpeg']),sha256:z.string().regex(/^[a-f0-9]{64}$/),width:positive.int(),height:positive.int(),originalWidth:positive.int(),originalHeight:positive.int(),exifOrientation:z.number().int().min(1).max(8),transform:z.literal('EXIF auto-oriented; display sRGB 8-bit'),original:z.string().max(160000000),display:z.string().max(160000000),warning:z.string()}).strict(),layout:z.object({left:z.number().int().min(0).max(10000),right:z.number().int().min(0).max(10000),top:z.number().int().min(0).max(10000),bottom:z.number().int().min(0).max(10000),background:color}).strict(),calibration:z.object({pixels:positive,realLength:positive,unit:z.enum(['μm','mm']),source:z.string(),isotropic:z.literal(true)}).nullable(),annotations:z.array(AnnotationSchema).max(2000),updatedAt:z.string()}).strict();
export type Project=z.infer<typeof ProjectSchema>; export type Annotation=z.infer<typeof AnnotationSchema>; export type Style=z.infer<typeof StyleSchema>; export type Tool='select'|Annotation['type'];
export const defaultStyle:Style={color:'#ef4444',strokeWidth:4,headSize:16,dash:false,contrast:true,fontSize:28,font:'BioSans',bold:false,align:'left',textOutline:false,background:'#ffffff',backgroundOpacity:0.85,fill:'#facc15',fillOpacity:0};
export const clone=<T>(v:T):T=>{if(v&&typeof v==='object'&&(v as any).format==='bio-annotation'){const {image,...mutable}=v as any;return {...structuredClone(mutable),image} as T;}return structuredClone(v);};
export function validate(v:unknown):Project{const p=ProjectSchema.parse(v);if(new Set(p.annotations.map(a=>a.id)).size!==p.annotations.length)throw Error('对象 ID 重复');if(p.annotations.some(a=>a.imageId!==p.image.id))throw Error('对象关联到未知图片');outputSize(p);return p;}
export function outputSize(p:Project,scale=1){if(![1,2,4].includes(scale))throw Error('倍率仅支持 1、2、4');const width=(p.image.width+p.layout.left+p.layout.right)*scale,height=(p.image.height+p.layout.top+p.layout.bottom)*scale;if(width>16384||height>16384||width*height>64000000)throw Error('输出超过限制：最长边 16384 像素、总计 6400 万像素。请减少留白或倍率。');return {width,height};}
export function screenToImage(x:number,y:number,view:{x:number;y:number;scale:number},layout:Project['layout']){return {x:(x-view.x)/view.scale-layout.left,y:(y-view.y)/view.scale-layout.top};}
export function zoomAt(view:{x:number;y:number;scale:number},x:number,y:number,scale:number){return {scale,x:x-(x-view.x)*scale/view.scale,y:y-(y-view.y)*scale/view.scale};}
export function move(a:Annotation,dx:number,dy:number,whole=false){a.geometry.x+=dx;a.geometry.y+=dy;if(a.type==='arrow'||a.type==='line'||(a.type==='callout'&&whole)){a.geometry.x2+=dx;a.geometry.y2+=dy;}}
export function patchAnnotation(p:Project,id:string,patch:unknown){const a=p.annotations.find(a=>a.id===id);if(!a)throw Error('对象 ID 不存在');const q=z.object({label:z.string().optional(),description:z.string().optional(),geometry:AnnotationSchema.shape.geometry.partial().optional(),style:StyleSchema.partial().optional(),visible:z.boolean().optional(),locked:z.boolean().optional(),status:AnnotationSchema.shape.status.optional()}).strict().parse(patch);Object.assign(a,q,{geometry:{...a.geometry,...q.geometry},style:{...a.style,...q.style}});return validate(p);}
export function markdown(p:Project){return `# ${p.title}\n\n${p.caption}\n\n图像：${p.image.name}（${p.image.width} × ${p.image.height} px）；修订号 ${p.revision}。\n坐标：方向校正后的原图左上角为 (0,0)，x 向右、y 向下；单位 px。图旁留白可使用负坐标。\n\n标注文字由用户或模型提供，软件未验证医学正确性。\n\n`+p.annotations.map(a=>`- **${a.label.replace(/\n/g,' / ')||a.type}** [${a.status}]\n  ID: ${a.id}；位置 (${a.geometry.x}, ${a.geometry.y}) px；${a.visible?'显示':'隐藏'}\n  ${a.description}\n`).join('\n');}
