import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import fs from 'node:fs/promises';import {createCanvas} from '@napi-rs/canvas';
import path from 'node:path';
import {validate,defaultStyle,move,screenToImage,zoomAt,outputSize,patchAnnotation,type Annotation} from '../src/model';import {renderProject} from '../src/render';
process.env.BIO_DATA_DIR='tests/storage';const {importImage,newProject,saveProject,readProject,packageProject,unpackProject,verifyResources,projectDir,scoped}=await import('../server/storage');const {exportPng}=await import('../server/export');
const c=createCanvas(1200,800),ctx=c.getContext('2d');ctx.fillStyle='#dcebf4';ctx.fillRect(0,0,1200,800);const image=await importImage(await c.encode('png'),'测试图.png');const base=newProject(image);
const annotation=():Annotation=>({id:randomUUID(),imageId:image.id,type:'callout',geometry:{x:900,y:200,x2:500,y2:300,width:230,height:70,unit:'image-pixel'},style:{...defaultStyle},label:'中文标签\n位置测试',description:'人工测试，不构成诊断',visible:true,locked:false,zIndex:0,status:'suggested'});
test('视口缩放/留白不改变原图坐标，鼠标中心缩放保持固定点',()=>{const v={x:22,y:33,scale:.6};const p={left:100,right:0,top:60,bottom:0,background:'#ffffff'};assert.deepEqual(screenToImage(322,213,v,p),{x:400,y:240});const v2=zoomAt(v,322,213,1.7);const q=screenToImage(322,213,v2,p);assert.ok(Math.abs(q.x-400)<1e-9&&Math.abs(q.y-240)<1e-9);});
test('关联文字移动保留尖端，整组移动同时改变尖端',()=>{const a=annotation();move(a,40,-20);assert.equal(a.geometry.x2,500);assert.equal(a.geometry.y2,300);move(a,10,10,true);assert.equal(a.geometry.x2,510);assert.equal(a.geometry.y2,310);});
test('项目校验拒绝版本、重复 ID、外来图像 ID 和无效尺寸',()=>{const p=structuredClone(base);p.annotations=[annotation()];assert.throws(()=>validate({...p,version:2}));assert.throws(()=>validate({...p,annotations:[p.annotations[0],p.annotations[0]]}));assert.throws(()=>validate({...p,annotations:[{...p.annotations[0],imageId:randomUUID()}]}));assert.throws(()=>patchAnnotation(p,p.annotations[0].id,{geometry:{width:-2}}));});
test('文档导出尺寸包含留白并同比例放大，拒绝超限尺寸',()=>{const p=structuredClone(base);p.layout={left:100,right:200,top:50,bottom:150,background:'#ffffff'};assert.deepEqual(outputSize(p),{width:1500,height:1000});assert.deepEqual(outputSize(p,2),{width:3000,height:2000});assert.throws(()=>outputSize({...p,image:{...p.image,width:6000,height:4000}},4));});
test('原子保存、重开资源、修订 CAS 并发及前版本备份',async()=>{const p=structuredClone(base);p.id=randomUUID();p.annotations=[annotation()];const saved=await saveProject(p,0);assert.equal(saved.revision,1);const reopened=await readProject(p.id);assert.equal(reopened.image.original,p.image.original);assert.deepEqual(reopened.annotations,p.annotations);const first=structuredClone(saved),second=structuredClone(saved);first.title='修订 A';second.title='修订 B';const results=await Promise.allSettled([saveProject(first,1),saveProject(second,1)]);assert.equal(results.filter(v=>v.status==='fulfilled').length,1);assert.equal(results.filter(v=>v.status==='rejected').length,1);assert.equal((await readProject(p.id)).revision,2);assert.ok(await fs.readFile(projectDir(p.id)+'/history/1.json','utf8'));});
test('便携包携带原图、标注和显示图，可移动重开，拒绝篡改',async()=>{const p=structuredClone(base);p.annotations=[annotation()];const packed=packageProject(p),restored=await unpackProject(packed);assert.deepEqual(restored,p);await assert.rejects(()=>unpackProject(Buffer.from('bad')));await assert.rejects(()=>verifyResources({...p,image:{...p.image,sha256:'0'.repeat(64)}}));});
test('EXIF 方向校正保留原资源，16 位 PNG 和 CMYK 被拒绝',async()=>{const sharp=(await import('sharp')).default;const jpeg=await sharp(await c.encode('png')).jpeg().withMetadata({orientation:6}).toBuffer();const oriented=await importImage(jpeg,'方向.jpg');assert.equal(oriented.width,800);assert.equal(oriented.height,1200);assert.equal(oriented.exifOrientation,6);assert.equal(oriented.original,jpeg.toString('base64'));const high=await sharp(await c.encode('png')).toColourspace('rgb16').png().toBuffer();await assert.rejects(()=>importImage(high,'16bit.png'));const cmyk=await sharp(jpeg).toColourspace('cmyk').jpeg().toBuffer();await assert.rejects(()=>importImage(cmyk,'CMYK.jpg'));});
test('PNG 合成像素尺寸、留白、透明填充及隐藏对象',async()=>{const p=structuredClone(base);p.layout.right=200;p.annotations=[annotation()];p.annotations[0].visible=false;const bytes=await exportPng(p);const sharp=(await import('sharp')).default,m=await sharp(bytes).metadata();assert.equal(m.width,1400);assert.equal(m.height,800);const pixel=await sharp(bytes).extract({left:1300,top:100,width:1,height:1}).raw().toBuffer();assert.deepEqual([...pixel],[255,255,255,255]);});

test('读写范围拒绝越界路径及目录符号链接',async()=>{const outside=path.resolve('tests/outside-storage');await fs.mkdir(outside,{recursive:true});await assert.rejects(()=>scoped(path.join(outside,'outside.txt')));const link=projectDir(randomUUID());await fs.symlink(outside,link,process.platform==='win32'?'junction':'dir');try{await assert.rejects(()=>scoped(path.join(link,'outside.txt')));}finally{await fs.unlink(link);}});
