import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {zipSync} from '../../../editions/v2.1-p/node_modules/fflate/esm/index.mjs';
const platform=path.dirname(fileURLToPath(import.meta.url)),workspace=path.resolve(platform,'../../../..'),edition=path.join(workspace,'source/editions/v2.1-p');
const name='Bio-Picture-Editor-v2.1-p',dest=path.join(workspace,'releases/windows/v2.1-p',name),docs=path.join(workspace,'docs/windows/v2.1-p');
await fs.mkdir(dest,{recursive:true});
for(const file of ['README.md','USAGE.md','CODEX_GUIDE.md','CHANGELOG.md','THIRD-PARTY-NOTICES.txt'])await fs.copyFile(path.join(docs,file),path.join(dest,file));
await fs.copyFile(path.join(platform,'README.md'),path.join(dest,'DESKTOP-BUILD.md'));
await fs.copyFile(path.join(workspace,'validation/v2.1-p/V2.1-P-REPORT.md'),path.join(dest,'V2.1-P-REPORT.md'));
for(const file of ['desktop-cli.ps1','Codex-CLI.cmd','NODE-LICENSE.txt','WEBVIEW2-LICENSE.txt','WEBVIEW2-NOTICE.txt'])await fs.copyFile(path.join(platform,file),path.join(dest,file));
for(const file of ['app-icon.svg','app-icon.png','app.ico'])await fs.copyFile(path.join(edition,'assets',file),path.join(dest,file));
await fs.copyFile(path.join(edition,'examples/example.biozip'),path.join(dest,'示例项目.biozip'));
await fs.copyFile(path.join(edition,'examples/IMAGE-LICENSE.md'),path.join(dest,'IMAGE-LICENSE.md'));
await fs.copyFile(path.join(edition,'public/fonts/LICENSE.txt'),path.join(dest,'FONT-LICENSE.txt'));
const guide=await fs.readFile(path.join(docs,'USAGE.md'),'utf8');
await fs.writeFile(path.join(dest,'操作指南.md'),guide);await fs.writeFile(path.join(dest,'先看这里-操作指南.txt'),guide);
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const inline=s=>escape(s).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>');
let body='',lines=guide.split(/\r?\n/),paragraph=[];
const flush=()=>{if(paragraph.length){body+='<p>'+inline(paragraph.join(' '))+'</p>';paragraph=[];}};
for(let n=0;n<lines.length;n++){let line=lines[n];if(!line.trim()){flush();continue;}const heading=line.match(/^(#{1,3}) (.*)$/);if(heading){flush();body+='<h'+heading[1].length+'>'+inline(heading[2])+'</h'+heading[1].length+'>';continue;}if(line.startsWith('|')){flush();let rows=[];while(n<lines.length&&lines[n].startsWith('|'))rows.push(lines[n++]);n--;body+='<table>';rows.filter(r=>!/^\|[\s|:-]+$/.test(r)).forEach((r,i)=>{body+='<tr>'+r.split('|').slice(1,-1).map(c=>'<'+(i?'td':'th')+'>'+inline(c.trim())+'</'+(i?'td':'th')+'>').join('')+'</tr>';});body+='</table>';continue;}paragraph.push(line);}flush();
await fs.writeFile(path.join(dest,'先看这里-操作指南.html'),'<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>生物图片编辑器 v2.1-p 操作指南</title><style>body{max-width:960px;margin:40px auto;padding:0 24px;background:#f6f8fc;color:#263446;font:15px/1.85 "Microsoft YaHei",sans-serif}main{background:white;padding:32px 40px;border-radius:16px}h1,h2{color:#235f9c}h2{margin-top:32px}code{background:#eef3f9;padding:2px 4px;border-radius:3px}table{border-collapse:collapse;width:100%;font-size:14px}td,th{border:1px solid #dce4ef;padding:8px 12px;text-align:left}th{background:#edf4fc}</style><main>'+body+'</main></html>');
const entries={};
for(const file of (await fs.readdir(dest)).sort()){const stat=await fs.stat(path.join(dest,file));if(!stat.isFile())throw Error('Unexpected release directory: '+file);if(file.endsWith('.exe.config'))continue;entries[name+'/'+file]=new Uint8Array(await fs.readFile(path.join(dest,file)));}
const archive=Buffer.from(zipSync(entries,{level:6})),zipFile=dest+'.zip';await fs.writeFile(zipFile,archive);
const sha=crypto.createHash('sha256').update(archive).digest('hex');await fs.writeFile(zipFile+'.sha256',sha+'  '+name+'.zip\n');
console.log(JSON.stringify({zipFile,bytes:archive.length,sha256:sha,fileCount:Object.keys(entries).length},null,2));
