import fs from 'node:fs/promises';import path from 'node:path';import {createHash,randomUUID} from 'node:crypto';import sharp from 'sharp';import {zipSync,unzipSync,strToU8,strFromU8} from 'fflate';import {validate,type Project,defaultStyle} from '../src/model';
export const root=path.resolve(process.env.BIO_DATA_DIR||'data');
export function projectDir(id:string){if(!/^[0-9a-f-]{36}$/.test(id))throw Error('非法项目 ID');return path.join(root,'projects',id);}
export async function scoped(file:string){const absolute=path.resolve(file);if(absolute!==root&&!absolute.startsWith(root+path.sep))throw Error('读写路径超出项目数据目录');const parts=path.relative(root,absolute).split(path.sep);let current=root;for(const part of ['',...parts]){if(part)current=path.join(current,part);try{if((await fs.lstat(current)).isSymbolicLink())throw Error('项目目录不允许符号链接');}catch(e:any){if(e.code!=='ENOENT')throw e;}}}
export async function atomic(file:string,bytes:string|Buffer){await scoped(file);await fs.mkdir(path.dirname(file),{recursive:true});const temp=file+'.'+randomUUID()+'.tmp';await fs.writeFile(temp,bytes);try{await fs.rename(temp,file);}catch(e){await fs.rm(temp,{force:true});throw e;}}
export async function importImage(bytes:Buffer,name:string){const m=await sharp(bytes,{limitInputPixels:64000000}).metadata();if(!['png','jpeg'].includes(m.format||''))throw Error('仅支持 PNG/JPEG 常见 8 位照片');if(m.depth!=='uchar'||m.space==='cmyk'||(m.pages||1)>1)throw Error('不支持高位深、CMYK 或多页图片，请明确转换为 8 位 sRGB PNG/JPEG 后导入');const {data,info}=await sharp(bytes).autoOrient().toColourspace('srgb').png().toBuffer({resolveWithObject:true});if(info.width*info.height>64000000)throw Error('图像超过 6400 万像素限制');return {id:randomUUID(),name:path.basename(name).slice(0,300),mime:m.format==='jpeg'?'image/jpeg' as const:'image/png' as const,sha256:createHash('sha256').update(bytes).digest('hex'),width:info.width,height:info.height,originalWidth:m.width!,originalHeight:m.height!,exifOrientation:m.orientation||1,transform:'EXIF auto-oriented; display sRGB 8-bit' as const,original:bytes.toString('base64'),display:data.toString('base64'),warning:m.hasProfile?'含色彩配置：显示及导出转换为 8 位 sRGB；原始文件完整保留，不能保证原位深/配置/元数据。':''};}
export function newProject(image:Project['image']):Project{return validate({format:'bio-annotation',version:1,id:randomUUID(),revision:0,title:image.name,caption:'',image,layout:{left:0,right:0,top:0,bottom:0,background:'#ffffff'},calibration:null,annotations:[],updatedAt:new Date().toISOString()});}
export async function verifyResources(p:Project){const bytes=Buffer.from(p.image.original,'base64');if(createHash('sha256').update(bytes).digest('hex')!==p.image.sha256)throw Error('原图 SHA256 不匹配');const actual=await importImage(bytes,p.image.name);if(actual.width!==p.image.width||actual.height!==p.image.height||actual.exifOrientation!==p.image.exifOrientation||actual.originalWidth!==p.image.originalWidth||actual.originalHeight!==p.image.originalHeight||actual.mime!==p.image.mime)throw Error('图片资源或尺寸/方向数据不匹配');if(actual.display!==p.image.display){const a=await sharp(Buffer.from(actual.display,'base64')).ensureAlpha().raw().toBuffer({resolveWithObject:true});const b=await sharp(Buffer.from(p.image.display,'base64')).ensureAlpha().raw().toBuffer({resolveWithObject:true});if(a.info.width!==b.info.width||a.info.height!==b.info.height||!a.data.equals(b.data))throw Error('显示图像素与原图方向校正结果不匹配');}}
export async function readProject(id:string){const dir=projectDir(id);await scoped(path.join(dir,'project.json'));const p=JSON.parse(await fs.readFile(path.join(dir,'project.json'),'utf8'));await scoped(path.join(dir,'original'+(p.image.mime==='image/jpeg'?'.jpg':'.png')));await scoped(path.join(dir,'display.png'));p.image.original=(await fs.readFile(path.join(dir,'original'+(p.image.mime==='image/jpeg'?'.jpg':'.png')))).toString('base64');p.image.display=(await fs.readFile(path.join(dir,'display.png'))).toString('base64');if(createHash('sha256').update(Buffer.from(p.image.original,'base64')).digest('hex')!==p.image.sha256)throw Error('原始图片损坏或被替换');return validate(p);}
export async function readMetadata(id:string){await scoped(path.join(projectDir(id),'project.json'));return validate(JSON.parse(await fs.readFile(path.join(projectDir(id),'project.json'),'utf8')));}
const queue=new Map<string,Promise<any>>();
export async function saveProject(project:Project,expected:number){const job=(queue.get(project.id)||Promise.resolve()).catch(()=>{}).then(async()=>{const p=validate(project);if(!Number.isInteger(expected)||expected<0)throw Error('修订号必须为非负整数');let old:Project|undefined;try{old=await readProject(p.id);}catch(e:any){if(e.code!=='ENOENT')throw e;}if((old?.revision||0)!==expected){const e:any=Error(`修订冲突：期望 ${expected}，当前 ${old?.revision||0}`);e.status=409;throw e;}if(!old||p.image.sha256!==old.image.sha256||p.image.display!==old.image.display){await verifyResources(p);if(old)throw Error('已保存项目不能替换底图，请新建项目');}const dir=projectDir(p.id);if(old)await atomic(path.join(dir,'history',`${old.revision}.json`),JSON.stringify({...old,image:{...old.image,original:'',display:''}},null,2));else{await atomic(path.join(dir,'original'+(p.image.mime==='image/jpeg'?'.jpg':'.png')),Buffer.from(p.image.original,'base64'));await atomic(path.join(dir,'display.png'),Buffer.from(p.image.display,'base64'));}p.revision=expected+1;p.updatedAt=new Date().toISOString();await atomic(path.join(dir,'project.json'),JSON.stringify({...p,image:{...p.image,original:'',display:''}},null,2));return p;});queue.set(project.id,job);try{return await job;}finally{if(queue.get(project.id)===job)queue.delete(project.id);}}
export function packageProject(p:Project){const v=validate(p);return Buffer.from(zipSync({'project.json':strToU8(JSON.stringify({...v,image:{...v.image,original:'',display:''}},null,2)),['original'+(v.image.mime==='image/jpeg'?'.jpg':'.png')]:Buffer.from(v.image.original,'base64'),'display.png':Buffer.from(v.image.display,'base64')},{level:6}));}
export async function unpackProject(bytes:Buffer){if(bytes.length>100000000)throw Error('项目包超过 100 MB');const files=unzipSync(bytes,{filter:f=>{if(f.originalSize>160000000)throw Error('解压资源过大');return ['project.json','original.jpg','original.png','display.png'].includes(f.name);}});if(!files['project.json']||!files['display.png'])throw Error('项目包缺少 JSON 或图片资源');const p=JSON.parse(strFromU8(files['project.json']));p.image.original=Buffer.from(files[p.image.mime==='image/jpeg'?'original.jpg':'original.png']||[]).toString('base64');p.image.display=Buffer.from(files['display.png']).toString('base64');const validated=validate(p);await verifyResources(validated);return validated;}
